### ISSUE TITLE
Shortcode name containing space are no more allowed as of WP 4.4.0

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-shortcodes#1]
Hi, fonts.json is parsed and transformed into shortcodes thanks to fonts.php. The thing is that fonts.json contains an element named "open sans" which can't anymore be used to named a shortcode.

I suggest to rename it to open-sans or open_sans.

Here is the error thrown by WP : 

```
Notice: add_shortcode was called incorrectly. Invalid shortcode name: open sans. 
Do not use spaces or reserved characters: & / < > [ ] Please see Debugging in WordPress for more information. 
(This message was added in version 4.4.0.) in /srv/www/tj-juice-test/wp/wp-includes/functions.php on line 3792
```

**Comment by ezekg** [comment]
Sorry, this should have been pushed upstream in the starter. I will do that now.

**Comment by ezekg** [comment]
Fixed in this commit, https://github.com/ezekg/theme-juice-starter/commit/002de5cc14b551e6c7139a7e77798f2b41ab0d43.
